n = input('digite algo: ')
print('è alfanumerico?', n.isalpha() )
#print('O tipo primitivo dele: ',(n.))
print ('È um numero: ',n.isnumeric())
print ('é alphanumerico: ', n.isalpha())
print ('tem espaco?: ',n.isspace())
print('tem decimal?  ',n.isdecimal())
print('so tem maiuscula? ', n.isupper())
print('So minusculo: ',n.islower())
print('esta capitalifazado? ',n.istitle())