nome = str(input('Digite seu nome:'))
print('convertido pra letra maiuscula:',nome.upper())
print('convertido pra letra minuscula:',nome.lower())
print('quantidade de letras com espaco:',len(nome))
separar = nome.split()
juntar = ''.join(separar)
print('quantidade de letra sem espaco:',len(juntar))
primeiro_nome = nome.split()
print('A primeira frase tem',len(primeiro_nome[0]),'letras')