nome = str(input('Digite seu nome:')).strip()
print('convertido pra letra maiuscula:',nome.upper())
print('convertido pra letra minuscula:',nome.lower())
print('quantidade de letras com espaco:',len(nome))
nome = nome.split()
juntar = ''.join(nome)
print('quantidade de letra sem espaco:',len(juntar))
print('A primeira frase tem',len(nome[0]),'letras')