nome = str(input('Digite uma frase motivadora: '))
nome = nome.lower()
print('A letra a aparece:',nome.count('a'), 'vezes')
print('A letra "A" aparece na primeira posição:'.format(nome.find('a')))
print('A letra "A" aparece na ultima posição:'.format(nome.rfind('a')))